---
name: Release

on:  # yamllint disable-line rule:truthy
  release:
    types:
      - published

jobs:
  release-web:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'web/')
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }} 
      - run: |
          echo "version=$(echo -n '${{ github.event.release.tag_name }}' | sed 's/web\///g')" >> "$GITHUB_OUTPUT"
        id: vars
      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: 69b10931.c1.gra9.container-registry.ovh.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Package and push helm chart to Amazon ECR
        id: build
        run: |
          helm package ${{ inputs.chart-path }} --version ${{ steps.vars.outputs.version }}
          helm push ${{ inputs.chart-name }}-${{ steps.vars.outputs.version }}.tgz oci://69b10931.c1.gra9.container-registry.ovh.net/schwifty-public/chart/web
      - name: Update release
        if: ${{ steps.build.conclusion == 'success' }}
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: oci://69b10931.c1.gra9.container-registry.ovh.net/schwifty-public/chart/web:${{ steps.vars.outputs.version }}

  release-agent:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'agent/')
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }} 
      - run: |
          echo "version=$(echo -n '${{ github.event.release.tag_name }}' | sed 's/agent\///g')" >> "$GITHUB_OUTPUT"
        id: vars
      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: 69b10931.c1.gra9.container-registry.ovh.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Package and push helm chart to Amazon ECR
        id: build
        run: |
          helm package ${{ inputs.chart-path }} --version ${{ steps.vars.outputs.version }}
          helm push ${{ inputs.chart-name }}-${{ steps.vars.outputs.version }}.tgz oci://69b10931.c1.gra9.container-registry.ovh.net/schwifty-public/chart/agent
      - name: Update release
        if: ${{ steps.build.conclusion == 'success' }}
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: oci://69b10931.c1.gra9.container-registry.ovh.net/schwifty-public/chart/agent:${{ steps.vars.outputs.version }}
